
# Configuration file for Mega-Linter
# See all available variables at https://nvuillam.github.io/mega-linter/configuration/ and in linters documentation


on:
  push:
  pull_request:
    branches: [master, main]

env:
  APPLY_FIXES: all # all, none, or list of linter keys

jobs:
  name: Cancel duplicate jobs
  runs-on: ubuntu-latest
  steps:
    - uses: fkirc/skip-duplicate-actions@master
    with:
      github_token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}

DEFAULT_BRANCH: master # Usually master or main
ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
DISABLE:
  - COPYPASTE # Comment to disable checks of abusive copy-pastes
  # - SPELL # Uncomment to enable checks of spelling mistakes # - SPELL # Uncomment to disable checks of spelling mistakes

FILEIO_REPORTER: false
PRINT_ALPACA: true
SHOW_ELAPSED_TIME: true
